---
- name: Update dnf cache
  dnf:
    update_cache: yes

- name: Install required packages for Nginx, PHP, and MySQL
  dnf:
    name: "{{ item }}"
    state: present
  with_items:
    - nginx
    - mariadb105-server
    - php
    - php-fpm
    - php-mysqlnd
    - python3-pip

- name: Install pip3
  dnf:
    name: python3-pip
    state: present

- name: Install Python MySQL client using pip (PyMySQL)
  pip:
    name: PyMySQL
    executable: pip3

- name: Start and enable Nginx
  service:
    name: nginx
    state: started
    enabled: true

- name: Start and enable MariaDB (MySQL)
  service:
    name: mariadb
    state: started
    enabled: true

- name: Set MySQL root password
  mysql_user:
    name: root
    password: "{{ db_password }}"
    login_user: root
    login_password: "{{ db_password }}"
    host_all: yes
    login_unix_socket: /var/lib/mysql/mysql.sock
    update_password: always

- name: Create WordPress database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ db_password }}"

- name: Create WordPress MySQL user
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ db_password }}"

- name: Ensure /var/www/html/wordpress directory exists
  file:
    path: /var/www/html/
    state: directory
    owner: nginx
    group: nginx
    mode: '0777'

- name: Download WordPress
  get_url:
    url: "{{ wordpress_url }}"
    dest: /tmp/wordpress.tar.gz

- name: Extract WordPress to {{ wordpress_install_dir }}
  unarchive:
    src: /tmp/wordpress.tar.gz
    dest: "{{ wordpress_install_dir }}"
    remote_src: yes
    creates: "{{ wordpress_install_dir }}/wp-settings.php"

- name: Set proper permissions for WordPress directory
  file:
    path: "{{ wordpress_install_dir }}"
    owner: nginx
    group: nginx
    recurse: yes

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: "{{ wordpress_config_dir }}"
    owner: nginx
    group: nginx

- name: Copy Nginx configuration for WordPress
  template:
    src: wordpress.nginx.j2
    dest: /etc/nginx/conf.d/wordpress.conf
  notify:
    - reload nginx
